GET http://localhost:6161/cards HTTP/1.1

####


GET http://localhost:6161/cards/653f9bd354c41827bafde31d

####

GET http://localhost:6161/cards/title?title= HTTP/1.1

####

GET http://localhost:6161/cardsPage?page=1 HTTP/1.1

####

POST http://localhost:6161/cards/create HTTP/1.1
Content-Type: application/json

{
  "title": "Nova",
  "cover": "https://i.postimg.cc/KYbhv8dk/spiderman.png",
 "newCardId":"654be1fd2f54327c7b7cc647"
}

####NEW CARD 
POST http://localhost:6161/comic/create HTTP/1.1
Content-Type: application/json

{
  "title": "Superior Spider-man #1",
  "cover": "https://images3.imgbox.com/28/04/jpGZo3YW_o.jpg",
  "price":"79,99€",
  "author":"Peter David, Rick Leonardi",
  "year":"Novembre 1992",
  "images":[
    "https://images3.imgbox.com/6a/f3/V3pFXipa_o.jpg",
    "https://images3.imgbox.com/b5/d4/R1nUH54e_o.jpg",
    "https://images3.imgbox.com/ce/fb/tHITYeA8_o.jpg",
    "https://images3.imgbox.com/17/11/ce1ECjoE_o.jpg"   
  ]
 }

####
GET http://localhost:6161/cards/654be21f2f54327c7b7cc649/comics
####
PATCH http://localhost:6161/cards/modify/6540f4186706d44ec39d0a22 HTTP/1.1
Content-Type: application/json

{
   
    "cover":"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/5b8d2b12-21e8-4931-8a6d-fb9ecdd60383/df191wv-2cbebba8-5515-4c84-93c4-c69b8f24f313.png/v1/fill/w_1280,h_1798/moon_knight_png_by_metropolis_hero1125_df191wv-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTc5OCIsInBhdGgiOiJcL2ZcLzViOGQyYjEyLTIxZTgtNDkzMS04YTZkLWZiOWVjZGQ2MDM4M1wvZGYxOTF3di0yY2JlYmJhOC01NTE1LTRjODQtOTNjNC1jNjliOGYyNGYzMTMucG5nIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.RgCboO8XJ_zRIljvnGhe5F6v1u7mPY96pjOMShRsAlQ"
}


####

DELETE http://localhost:6161/cards/delete/653c2e4d974b64398c6fe25c HTTP/1.1


####
GET http://localhost:6161/users HTTP/1.1

####

POST http://localhost:6161/users/create HTTP/1.1
Content-Type: application/json

{ 
  "firstName": "Mario",
  "lastName": "Rossi",
  "email": "MarioRossi@gmail.com",
  "password": "lamiapassword",
  "role":"user"

}



####COMMENTS

POST  http://localhost:6161/cards/654be21f2f54327c7b7cc649/comment/create HTTP/1.1
Content-Type: application/json

{ 
  "username": "Mario",
  "content": "Rossi",
   "code":"654be21f2f54327c7b7cc649"

}

####
GET  http://localhost:6161/comments/653ff6fb6706d44ec39d0920 HTTP/1.1

####

GET  http://localhost:6161/comments/getById/654a5a64a0de9ee981eb295e HTTP/1.1

####

PUT http://localhost:6161/cards/653ff6fb6706d44ec39d0920/comments/654a5a64a0de9ee981eb295e/modify
Content-Type: application/json

{ 
  "username": "Marietto",
  "content": "Rossetto",
   "code":"653ff6fb6706d44ec39d0920"

}