GET http://localhost:6161/cards HTTP/1.1

####


GET http://localhost:6161/cards/65540a55235b366349ec715f

####

GET http://localhost:6161/cards/title?title= HTTP/1.1

####

GET http://localhost:6161/cardsPage?page=1 HTTP/1.1

####

POST http://localhost:6161/cards/create HTTP/1.1
Content-Type: application/json

{
  "title": "Gambit",
  "cover":"https://i.postimg.cc/rFLy0JpR/gambit.png"
}

####NEW CARD 
POST http://localhost:6161/cards/6553ff71235b366349ec70eb/comic/create HTTP/1.1
Content-Type: application/json

{
  "title": "Doctor Strange 1: Sorcerer Supreme of the Galaxy",
  "cover":"https://i.postimg.cc/bvcqh5PC/photo-2023-11-15-00-44-57.jpg",
  "price":12.99,
  "author":"Jesus Saiz, Mark Waid",
  "year":"Novembre 2020",
  "images":[
"https://i.postimg.cc/B6N32QKk/photo-2023-11-15-00-44-58.jpg",
"https://i.postimg.cc/yNmsYTYV/photo-2023-11-15-00-44-59.jpg",
"https://i.postimg.cc/vBGM16c5/photo-2023-11-15-00-45-00.jpg",
"https://i.postimg.cc/L5XpDKkX/photo-2023-11-15-00-45-01.jpg"
  ],
  "newCardId":"6553ff71235b366349ec70eb"
 }
####
PATCH http://localhost:6161/comic/6553fd17235b366349ec7096/modify HTTP/1.1
Content-Type: application/json

{

  "author":"Mike Carey, Scott Kolins"
}
####
GET http://localhost:6161/comic/654d04fc2511150e52a1b52c
####
GET http://localhost:6161/cards/654d1351297dd56addeda53f/comics  HTTP/1.1
####
PATCH http://localhost:6161/cards/modify/65541e8e9e5ab27fe22d459b HTTP/1.1
Content-Type: application/json

{
     "title": "Galactus",
    "cover":"https://i.postimg.cc/Qtq6tFT9/galactus.png"
}


####

DELETE http://localhost:6161/cards/delete/653c2e4d974b64398c6fe25c HTTP/1.1


####
GET http://localhost:6161/users HTTP/1.1

####

POST http://localhost:6161/users/create HTTP/1.1
Content-Type: application/json

{ 
  "firstName": "Mario",
  "lastName": "Rossi",
  "email": "MarioRossi@gmail.com",
  "password": "lamiapassword",
  "role":"user"

}



####COMMENTS

POST  http://localhost:6161/cards/654d0b9e809adbcb762ada5d/comment/create HTTP/1.1
Content-Type: application/json

{ 
  "username": "Mario",
  "content": "Commento prova code",
   "code":"654d0b9e809adbcb762ada5d"

}

####
GET  http://localhost:6161/cards/654d0b9e809adbcb762ada5d/comments HTTP/1.1

####

GET  http://localhost:6161/comments/getById/654cfcd3a4b53f58d07fda41 HTTP/1.1

####

PUT http://localhost:6161/cards/653ff6fb6706d44ec39d0920/comments/654a5a64a0de9ee981eb295e/modify
Content-Type: application/json

{ 
  "username": "Marietto",
  "content": "Rossetto",
   "code":"653ff6fb6706d44ec39d0920"

}